# Generated by Django 5.0.1 on 2024-01-21 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desafio',
            name='status',
            field=models.CharField(blank=-1, choices=[('NRD', 'Não realizado'), ('NTD', 'Não terminado'), ('FND', 'Finalizado')], max_length=3, null=True),
        ),
    ]
