# Generated by Django 5.0.1 on 2024-01-21 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0002_alter_desafio_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desafio',
            name='status',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
